### ISSUE TITLE
iOS9下调试会导致statusBar消失

### ISSUE THREAD

**Issue by ZhangCrow** [remember17/WHDebugTool#2]
如题 iOS9下调试会导致statusBar消失

**Comment by Gentear** [comment]
+1 看了别人的解决办法是重写controller  实现状态栏的两个方法，然后把rootVC指向 ，然后状态栏的状态从外面传进来，看作者怎么处理了，设置UIWindowLevelAlert感觉不是一个好方法

**Comment by remember17** [comment]
修复了，pod 'WHDebugTool', '~> 1.5'
