### ISSUE TITLE
定时器释放后，需要设置为nil么？

### ISSUE THREAD

**Issue by saling** [remember17/WHDebugTool#8]
我这边使用该工具后，在_displayLink invalidate 行 出现了 EXC_BAD_ACCESS 异常
- (void)stopMonitoring {
    [_displayLink invalidate];
}

是否需要添加设置为nil呀？
    _displayLink = nil;

**Comment by remember17** [comment]
added

**Comment by remember17** [comment]
> 我这边使用该工具后，在_displayLink invalidate 行 出现了 EXC_BAD_ACCESS 异常
> 
> * (void)stopMonitoring {
>   [_displayLink invalidate];
>   }
> 
> 是否需要添加设置为nil呀？
> _displayLink = nil;

added
